### ISSUE TITLE
Japanese document causes error

### ISSUE THREAD

**Issue by ryanflee** [TAUSBV/dqf-api#45]
Japanese seems to be completely broken in the latest version (0.97). Whenever I try to open the translated Japanese document, I get the error shown below. When I click "OK", Trados closes the document and returns to the Files view.

Error:
```
'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Dqf.PluginResources.resources" was correctly embedded or linked into assembly "Dqf" at compile time, or that all the satellite assemblies required are loadable and fully signed.'
```

Stack trace: 
```
at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
   at Dqf.PluginResources.get_warning()
   at Dqf.DqfErrorForm.InitializeComponent()
   at Dqf.DqfErrorForm..ctor(DqfException de)
   at Dqf.DqfClient.AssignTask(String translatorKey, String projectKey, Int64 project_id, String target_language, String file_name)
   at Dqf.MeasureSuggestProvider.ReadTaskID(ProjectsController pc)
   at Dqf.MeasureSuggestProvider.OnActiveDocumentChanged()
   at Sdl.TranslationStudioAutomation.IntegrationApi.AutoSuggest.AbstractAutoSuggestProvider.doc_ActiveDocumentChanged(Object sender, EventArgs e)
   at Sdl.TranslationStudioAutomation.IntegrationApi.AutoSuggest.AbstractAutoSuggestProvider.Initialize()
   at Sdl.TranslationStudioAutomation.IntegrationApi.Internal.ExtensionBuilders.AutoSuggestProviderBuilder.Build(IExtension extension, Object defaultInstance, ExtensionArguments arguments)
   at Sdl.Core.PluginFramework.Integration.ExtensionsRepository.AddExtension[TResult](IExtension extension, ExtensionArguments arguments, Func`4 instanceCreator)
   at Sdl.Core.PluginFramework.Integration.ExtensionsRepository.AddExtension[TResult](IExtension extension, ExtensionArguments arguments, Func`4 instanceCreator)
   at Sdl.Core.PluginFramework.Integration.ExtensionBuilderFactory.Build[TResult](IExtension extension, ExtensionArguments arguments, Boolean useCache)
   at Sdl.Core.PluginFramework.Integration.ExtensionBuilderFactory.<>c__DisplayClass1`2.<Build>b__0(IExtension extension)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sdl.Core.PluginFramework.Integration.ExtensionBuilderFactory.Build[TAttribute,TResult](ExtensionArguments arguments, Boolean useCache)
   at Sdl.Core.PluginFramework.Integration.ExtensionsFactory.Create[TAttribute,TResult](ExtensionArguments arguments, Boolean useCache)
   at Sdl.TranslationStudio.Editor.TranslationEditor.Intellisense.SuggestionDataProvidersFactory.CreateSuggestionDataProviders(IEditorService editorService, ITranslatableDocumentEditorSettings editorSettings, TranslationMemorySettings translationMemorySettings)
   at Sdl.TranslationStudio.Editor.TranslationEditor.Intellisense.IntellisenseEditing.Hook(ITranslatableDocument doc, ITranslatableDocumentEditingView documentEditingView)
   at Sdl.TranslationStudio.Editor.TranslationEditor.SideBySideDocumentEditingView.HookIntellisense()
   at Sdl.TranslationStudio.Editor.EditorService.document_Loaded(IDocument document)
   at Sdl.TranslationStudio.Api.Editor.AbstractInternalDocument.OnLoaded()
   at Sdl.TranslationStudio.Editor.TranslationEditor.TranslatableDocument.OnLoaded()
   at Sdl.TranslationStudio.Api.Editor.AbstractInternalDocument.AfterLoad(IJob job)
```

**Comment by HenkBoxma** [comment]
Hi Ryan,

This is a bug that I fixed in 0.98. I added an icon to the error dialog,
but it could not find that resource. I will send you the latest plugin.
Unfortunately, that one has still the issue with the segments.

Thanks,

Henk

Kind regards,
Henk Boxma

_________________________________________________________________
*Boxma IT (*www.henkboxma.com)
office:      +31 (318) 78 6002
mobile:    +31 (6) 4913 1863
skype:      henk_boxma
address:   Burgemeester Prinslaan 3, 6711 KA  Ede, The Netherlands
_________________________________________________________________

**Comment by HenkBoxma** [comment]
One if the problems was that the metadata was not saved (anymore) with the project. This could have caused the issue. I did tests with Japanese and the segments are now counted correctly:
![image](https://cloud.githubusercontent.com/assets/11646718/8228266/b8044022-15ad-11e5-9969-a7e4d93c395f.png)

**Comment by ryanflee** [comment]
I just confirmed your findings, Henk - no more Japanese errors and the segments are counted correctly, as you say. Thanks!

**Comment by HenkBoxma** [comment]
Welcome! Glad it works now

-Henk Boxma.
